apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-developer-portal
  namespace: cattle-portal
  labels:
    app: rancher-developer-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rancher-developer-portal
  template:
    metadata:
      labels:
        app: rancher-developer-portal
    spec:
      volumes:
        - name: tls-secret-volume
          secret:
            secretName: portal-app-tls
      # serviceAccountName: suse-manager-service-account
      containers:
      - image: nwmac/portal
        name: rancher-developer-portal
        command: ["/bin/sh"]
        args: ["-c", "/app/run.sh"]
        volumeMounts:
          - name: tls-secret-volume
            readOnly: true
            mountPath: "/etc/tls-secrets"
        env:
        - name: BS_TITLE
          value: "{{ .Values.title }}"
        - name: BS_NAME
          value: "{{ .Release.Name }}"
        - name: BS_NAMESPACE
          value: "{{ .Release.Namespace }}"
        - name: BS_SERVER_URL
          valueFrom:
            secretKeyRef:
              name: portal-app-config
              key: server-url
        - name: BS_K8S_TOKEN
          valueFrom:
            secretKeyRef:
              name: portal-token
              key: token
