---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: portal-read-only
rules:
  - apiGroups:
      - 'management.cattle.io'
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - '*'
    resources:
      - pods
      - configmaps
      - services
      - deployments
      - replicasets
      - horizontalpodautoscalers
      - ingresses
      - statefulsets
      - limitranges
      - resourcequotas
      - daemonsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - metrics.k8s.io
    resources:
      - pods
    verbs:
      - get
      - list
---      
apiVersion: v1
kind: ServiceAccount
metadata:
  name: portal
  namespace: cattle-portal
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: portal-read-only-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: portal-read-only
subjects:
- kind: ServiceAccount
  name: portal
  namespace: cattle-portal
---
apiVersion: v1
kind: Secret
metadata:
  name: portal-token
  namespace: cattle-portal
  annotations:
    kubernetes.io/service-account.name: portal
type: kubernetes.io/service-account-token