apiVersion: v1
kind: Secret
metadata:
  name: portal-app-config
  namespace: cattle-portal
spec:
  serverUrl: {{ .Values.rancher.serverUrl | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: portal-app-token
  namespace: cattle-portal
  annotations:
    kubernetes.io/service-account.name: "portal-service-account"
