apiVersion: v1
kind: Secret
metadata:
  name: portal-app-config
  namespace: cattle-portal
data:
  server-url: {{ .Values.rancher.serverUrl | b64enc }}
---
{{- $cert := genSelfSignedCertWithKey "" (list) (list) 3650 (genPrivateKey "rsa") }}
apiVersion: v1
kind: Secret
metadata:
  name: portal-app-tls
  namespace: cattle-portal
type: kubernetes.io/tls
data:
  tls.crt: |
    {{ $cert.Cert | b64enc }}
  tls.key: |
    {{ $cert.Key | b64enc }}
