apiVersion: v1
kind: Service
metadata:
  name: rancher-developer-portal
  namespace: cattle-portal
spec:
  type: ClusterIP
  ports:
  - name: "rancher-developer-portal"
    port: 7007
  selector:
    app: rancher-developer-portal
